spring:
  datasource:
    url: jdbc:h2:mem:bmdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      "hibernate.format_sql": true
      "hibernate.jdbc.time_zone": Asia/Seoul
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# App-specific settings (reserved for future use)

logging:
  level:
    "org.hibernate.sql": warn
    "org.springframework": info

---
spring:
  mvc:
    format:
      date: yyyy-MM-dd
  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false
